### ISSUE TITLE
Segmentation fault when using genetic map

### ISSUE THREAD

**Issue by GenevieveKrause** [odelaneau/shapeit5#101]
I am attempting to run phase_common_static from the docker image loaded from shapeit5_v5.1.1.docker.tar.gz on the All of Us research platform. I was able to successfully run the program using the following command:  
`phase_common_static --input E300-2024-06-05.vcf.gz --region chr20  --output E300-phase_common-map.bcf --thread 8`
However, when I added the --map to the same dataset I got a seg fault. 
`phase_common_static --input E300-2024-06-05.vcf.gz --region chr20  --map chr20.b38.gmap.gz  --output E300-phase_common-map.bcf --thread 8`
Here is what the output looks like:
`[SHAPEIT5] phase_common (jointly phase multiple common markers)
  * Author        : Olivier DELANEAU, University of Lausanne
  * Contact       : olivier.delaneau@gmail.com
  * Version       : 5.1.1 / commit = 990ed0d / release = 2023-05-08
  * Run date      : 05/06/2024 - 20:43:41

Files:
  * Input         : [/mnt/data/mount/gs/fc-secure-60ad3bba-4af3-4245-b945-479d3e9eb953/microarry-vcfs/E300-2024-06-05.vcf.gz]
  * Genetic Map   : [/mnt/data/mount/gs/fc-secure-60ad3bba-4af3-4245-b945-479d3e9eb953/genetic_maps/chr20.b38.gmap.gz]
  * Output        : [/mnt/data/output/gs/fc-secure-60ad3bba-4af3-4245-b945-479d3e9eb953/shapeit/E300-phase_common-map.bcf]
  * Output format : [bcf]

Parameters:
  * Seed    : 15052011
  * Threads : 8 threads
  * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
  * PBWT    : [window = 4cM / depth = auto / modulo = auto / mac = 5 / missing = 0.1]
  * HMM     : [window = 4cM / Ne = 15000 / Recombination rates given by genetic map]

Reading genotype data:
  * VCF/BCF scanning done (7.82s)
      + Variants [#sites=43173 / region=chr20]
      + Samples [#target=300 / #reference=0]
  * VCF/BCF parsing done (7.37s)
      + Genotypes [0/0=74.701%, 0/1=13.389%, 1/1=7.347%, ./.=4.564%, 0|1=0.000%]

Setting up genetic map:
  * GMAP parsing [n=0] (0.11s)
/mnt/data/script/shapeit-e300: line 4:     7 Segmentation fault      (core dumped) `

Unfortunately, because I am running this using data from the All of Us platform I am unable to share the files.

**Comment by dtaliun** [comment]
Hi @GenevieveKrause ,

`GMAP parsing [n=0] (0.11s)` indicates that it read 0 lines from your `chr20.b38.gmap.gz` file. Could it be that the file is empty, or something went wrong when mounting data to the image?

If there were 0 positions read from the genetic map file, then this [line inside variant_map::interpolateCentiMorgan](https://github.com/odelaneau/shapeit5/blob/c44cd044acb97d85541b5f56833ed06d6dc7a8ad/phase_common/src/containers/variant_map.cpp#L104) will result in segmentation fault because it assumes that the vector holding genetic map coordinates is never empty and accesses the first element using `[]` operator.

**Comment by GenevieveKrause** [comment]
Hello,

You were correct. The file got corrupted somewhere in the process.  I got a clean copy of the file and it worked fine.  Thank you.
